# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            ksw의 삽질연대기
# tagline:          '삽질연대기'
description:      '티스토리로 옮겼습니다<br>https://lifetutorial.tistory.com/'
url:              https://kwonsoonwoo.github.io/
baseurl:          ''

author:
  name:           '권순우'
  # url:            https://twitter.com/fongandrewc

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo: https://github.com/KwonSoonWoo/kwonsoonwoo.github.io

disqus:
  shortname: ksw-blog
