# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Ksw
tagline:          'A Jekyll theme'
description:      'Development story of non-professional'
url:              https://kwonsoonwoo.github.io/
baseurl:

author:
  name:           'Andrew Fong'
  url:            https://twitter.com/fongandrewc

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            3.6.0
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/fongandrew/hydeout

disqus.shortname:   ksw-blog
